# Secret for credentials.  By defining this as stringData:
# instead of data: we can enter details here in plain text and
# it gets base64 encoded when added to the system.
#
# Leave unused variables defined, but empty ""
#
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:
  # NOT base64
  GARMIN_USERNAME: "someone@example.com"
  GARMIN_PASSWORD: "password-goes-here"
  TRAINERROAD_PASSWORD: ""
  TRAINERROAD_USERNAME: ""

